services:
  - type: web
    name: shopee-shortener
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: BASE_URL
        value: https://shortlink.mindpilot.online
      - key: SHORTENER_BASE_URL
        value: https://shortlink.mindpilot.online
